global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: prom-read

remote_read:
- url: http://prometheus1:9090/read
  remote_timeout: 30s
  read_recent: true

- url: http://prometheus2:9090/read
  remote_timeout: 30s
  read_recent: true
